import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
//components
import Navbar from "../components/navbar/index";
import IntoCard from "../components/IntroCard/IntroCard";
import AboutMeCard from '../components/AboutMeCard/AboutMeCard';
import ExperienceCard from '../components/ExperienceCard/ExperienceCard';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Monalisha Mishra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.container}>
        <IntoCard />
        <AboutMeCard/>
        <ExperienceCard/>
      </div>
    </>
  );
};

export default Home;
